# jojolion Kitty theme

# core colours
background           #232127
foreground           #FDB153
cursor               #FDB153
selection_background #49474E
selection_foreground #232127

# standard 8 colours
color0  #232127
color1  #49474E
color2  #80A5B2
color3  #8FA0A6
color4  #ABDCED
color5  #B78445
color6  #BD8DA6
color7  #BE853E

# bright 8 Colours
color8  #BE8CA1
color9  #BF8741
color10 #CCE5EE
color11 #E2F3F9
color12 #EFD2A6
color13 #F4B05C
color14 #FCBBDD
color15 #FDB153
